services:
  - type: web
    name: emotion-ai-flask
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install torch==2.6.0+cu124 torchvision==0.17.0+cu124 torchaudio==2.6.0+cu124 --index-url https://download.pytorch.org/whl/cu124
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587